#!/bin/bash

while read local_ref local_sha remote_ref remote_sha
do
    if [[ $remote_ref =~ /master$ ]]
    then
        read -p "You're about to push master, is that what you intended? (y|n) " -n 1 -r < /dev/tty
        if ! [[ $REPLY =~ ^[Yy]$ ]]
        then
            echo
            echo "Aborting!"
            exit 1 
        fi
    fi
    if [[ $remote_ref =~ /main$ ]]
    then
        read -p "You're about to push main, is that what you intended? (y|n) " -n 1 -r < /dev/tty
        if ! [[ $REPLY =~ ^[Yy]$ ]]
        then
            echo
            echo "Aborting!"
            exit 1 
        fi
    fi
done

command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting '.git/hooks/pre-push'.\n"; exit 2; }
git lfs pre-push "$@"
